// Objective-C API for talking to github.com/yichengchen/clashX/ClashX Go package.
//   gobind -lang=objc github.com/yichengchen/clashX/ClashX
//
// File is generated by gobind. Do not edit.

#ifndef __GoClash_H__
#define __GoClash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL GoClashCheckPortAvailable(long port);

FOUNDATION_EXPORT NSString* _Nonnull GoClashClashGetConfigs(void);

FOUNDATION_EXPORT void GoClashClashSetupLogger(void);

FOUNDATION_EXPORT void GoClashClashSetupTraffic(void);

FOUNDATION_EXPORT NSString* _Nonnull GoClashClashUpdateConfig(NSString* _Nullable path);

/**
 * export Clash_checkSecret
 */
FOUNDATION_EXPORT NSString* _Nonnull GoClashClash_checkSecret(void);

FOUNDATION_EXPORT void GoClashClash_closeAllConnections(void);

FOUNDATION_EXPORT NSString* _Nonnull GoClashClash_getCountryForIp(NSString* _Nullable ip);

FOUNDATION_EXPORT NSString* _Nonnull GoClashClash_getProggressInfo(void);

FOUNDATION_EXPORT void GoClashClash_setSecret(NSString* _Nullable secret);

FOUNDATION_EXPORT NSString* _Nonnull GoClashGetRawCfg(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GoClashGetTcpNetList(void);

FOUNDATION_EXPORT NSString* _Nonnull GoClashGetUDpList(void);

FOUNDATION_EXPORT void GoClashInitClashCore(void);

FOUNDATION_EXPORT BOOL GoClashIsAddrValid(NSString* _Nullable addr);

FOUNDATION_EXPORT NSString* _Nonnull GoClashParseDefaultConfigThenStart(BOOL checkPort, BOOL allowLan, long proxyPort, NSString* _Nullable externalController, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable GoClashReadConfig(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GoClashRun(BOOL checkConfig, BOOL allowLan, long portOverride, NSString* _Nullable externalController);

FOUNDATION_EXPORT void GoClashSetConfigPath(NSString* _Nullable path);

FOUNDATION_EXPORT void GoClashSetHomeDir(NSString* _Nullable path);

FOUNDATION_EXPORT void GoClashSetUIPath(NSString* _Nullable path);

FOUNDATION_EXPORT NSString* _Nonnull GoClashVerifyClashConfig(NSString* _Nullable content);

FOUNDATION_EXPORT BOOL GoClashVerifyGEOIPDataBase(void);

#endif
