
// Objective-C API for talking to the following Go packages
//
//	github.com/yichengchen/clashX/ClashX
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libclash_FRAMEWORK_H__
#define __Libclash_FRAMEWORK_H__

#include "GoClash.objc.h"
#include "Universe.objc.h"

#endif
